name: 'spacex_dbt_project'
version: '1.0.0'

# Specify where dbt should find your models and sources
model-paths: ["models"]
source-paths: ["models"]

# Configuration for models
models:
  spacex_dbt_project:
    +schema: public        # The Redshift schema where the dbt models will be materialized
    +materialized: table   # Use 'table' to overwrite the data on each run
