# this file is used to define the standard tests that can be performed on the final dataframe
# unique: Ensures that a column (e.g., launch_id in launches) contains only unique values.
# not_null: Ensures that a column (e.g., launch_id, name, date_utc) does not contain any null values.
# relationships: Ensures referential integrity between the cores table and the launches table.


version: 2

models:
  - name: launches          # Reference the existing 'launches' table in Redshift
    description: "SpaceX launches data in Redshift"
    columns:
      - name: launch_id
        description: "Unique identifier for each launch"
        tests:
          - unique
          - not_null
      - name: date_utc
        description: "UTC date of the launch"
        tests:
          - not_null
          - expression_is_true:
              expression: "date_utc > '2006-01-01'"      
    

  - name: cores             # Reference the existing 'cores' table in Redshift
    description: "SpaceX cores data in Redshift"
    columns:
      - name: core
        description: "Unique identifier for each core"
        tests:
          - unique
          - not_null
  
        
